-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  table_name character varying NOT NULL,
  record_id uuid NOT NULL,
  action character varying NOT NULL CHECK (action::text = ANY (ARRAY['INSERT'::character varying::text, 'UPDATE'::character varying::text, 'DELETE'::character varying::text])),
  old_data jsonb,
  new_data jsonb,
  user_id uuid,
  user_email character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  woocommerce_id integer,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  company character varying,
  email character varying NOT NULL,
  phone character varying,
  address text,
  city character varying,
  postal_code character varying,
  country character varying DEFAULT 'Maroc'::character varying,
  ice character varying,
  notes text,
  billing_data jsonb,
  shipping_data jsonb,
  user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.delivery_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  number character varying NOT NULL UNIQUE,
  invoice_id uuid,
  customer_id uuid,
  customer_data jsonb,
  date date NOT NULL,
  estimated_delivery_date date,
  actual_delivery_date date,
  status character varying NOT NULL CHECK (status::text = ANY (ARRAY['draft'::character varying::text, 'in_transit'::character varying::text, 'delivered'::character varying::text, 'cancelled'::character varying::text])),
  items jsonb DEFAULT '[]'::jsonb,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT delivery_notes_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_notes_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT delivery_notes_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.document_numbers (
  id uuid NOT NULL,
  document_type text NOT NULL CHECK (document_type = ANY (ARRAY['INVOICE'::text, 'SALES_JOURNAL'::text, 'QUOTE'::text, 'DELIVERY'::text, 'RETURN'::text, 'PURCHASE_ORDER'::text])),
  number text NOT NULL UNIQUE,
  year integer NOT NULL,
  sequence integer NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  order_id bigint,
  journal_id uuid,
  CONSTRAINT document_numbers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.invoice_sequences (
  id integer NOT NULL DEFAULT nextval('invoice_sequences_id_seq1'::regclass),
  document_type character varying NOT NULL UNIQUE,
  prefix character varying NOT NULL DEFAULT ''::character varying,
  current_number integer NOT NULL DEFAULT 1,
  suffix character varying NOT NULL DEFAULT ''::character varying,
  reset_period character varying NOT NULL DEFAULT 'yearly'::character varying,
  last_reset_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT invoice_sequences_pkey PRIMARY KEY (id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  number character varying NOT NULL UNIQUE,
  woocommerce_order_id integer,
  customer_id uuid,
  date date NOT NULL,
  due_date date NOT NULL,
  status character varying NOT NULL CHECK (status::text = ANY (ARRAY['draft'::character varying::text, 'sent'::character varying::text, 'paid'::character varying::text, 'overdue'::character varying::text, 'cancelled'::character varying::text])),
  subtotal numeric NOT NULL DEFAULT 0,
  tax_rate numeric NOT NULL DEFAULT 20.00,
  tax_amount numeric NOT NULL DEFAULT 0,
  total numeric NOT NULL DEFAULT 0,
  currency character varying NOT NULL DEFAULT 'MAD'::character varying,
  notes text,
  payment_method character varying,
  payment_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  customer_info jsonb,
  line_items jsonb,
  woocommerce_status text,
  last_synced_at timestamp with time zone,
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.purchase_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  number character varying NOT NULL UNIQUE,
  supplier_id uuid,
  supplier_data jsonb,
  date date NOT NULL,
  expected_delivery_date date,
  status character varying NOT NULL CHECK (status::text = ANY (ARRAY['draft'::character varying::text, 'sent'::character varying::text, 'confirmed'::character varying::text, 'received'::character varying::text, 'cancelled'::character varying::text])),
  items jsonb DEFAULT '[]'::jsonb,
  subtotal numeric NOT NULL DEFAULT 0,
  tax_rate numeric NOT NULL DEFAULT 20.00,
  tax_amount numeric NOT NULL DEFAULT 0,
  total numeric NOT NULL DEFAULT 0,
  currency character varying NOT NULL DEFAULT 'MAD'::character varying,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT purchase_orders_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_orders_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.quotes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  number character varying NOT NULL UNIQUE,
  customer_id uuid,
  customer_data jsonb,
  date date NOT NULL,
  expiry_date date,
  status character varying NOT NULL CHECK (status::text = ANY (ARRAY['draft'::character varying::text, 'sent'::character varying::text, 'accepted'::character varying::text, 'rejected'::character varying::text, 'expired'::character varying::text])),
  items jsonb DEFAULT '[]'::jsonb,
  subtotal numeric NOT NULL DEFAULT 0,
  tax_rate numeric NOT NULL DEFAULT 20.00,
  tax_amount numeric NOT NULL DEFAULT 0,
  total numeric NOT NULL DEFAULT 0,
  currency character varying NOT NULL DEFAULT 'MAD'::character varying,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quotes_pkey PRIMARY KEY (id),
  CONSTRAINT quotes_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.return_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  number character varying NOT NULL UNIQUE,
  invoice_id uuid,
  delivery_note_id uuid,
  customer_id uuid,
  customer_data jsonb,
  date date NOT NULL,
  status character varying NOT NULL CHECK (status::text = ANY (ARRAY['draft'::character varying::text, 'processed'::character varying::text, 'cancelled'::character varying::text])),
  items jsonb DEFAULT '[]'::jsonb,
  reason text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT return_notes_pkey PRIMARY KEY (id),
  CONSTRAINT return_notes_delivery_note_id_fkey FOREIGN KEY (delivery_note_id) REFERENCES public.delivery_notes(id),
  CONSTRAINT return_notes_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT return_notes_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id)
);
CREATE TABLE public.sales_journal (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  number character varying NOT NULL UNIQUE,
  date date NOT NULL UNIQUE,
  status character varying NOT NULL DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying::text, 'validated'::character varying::text])),
  orders_included ARRAY DEFAULT '{}'::integer[],
  lines jsonb NOT NULL DEFAULT '[]'::jsonb,
  totals jsonb NOT NULL DEFAULT '{}'::jsonb,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sales_journal_pkey PRIMARY KEY (id)
);
CREATE TABLE public.settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  settings_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT settings_pkey PRIMARY KEY (id),
  CONSTRAINT settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.suppliers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  company character varying,
  email character varying,
  phone character varying,
  address text,
  city character varying,
  postal_code character varying,
  country character varying DEFAULT 'Maroc'::character varying,
  ice character varying,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT suppliers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.woocommerce_orders (
  id integer NOT NULL,
  number character varying NOT NULL,
  status character varying NOT NULL,
  currency character varying NOT NULL DEFAULT 'MAD'::character varying,
  date_created timestamp with time zone NOT NULL,
  date_modified timestamp with time zone,
  total numeric NOT NULL,
  total_tax numeric,
  shipping_total numeric,
  shipping_tax numeric,
  customer_id integer,
  billing jsonb,
  shipping jsonb,
  line_items jsonb,
  tax_lines jsonb,
  order_data jsonb,
  user_id uuid NOT NULL,
  synced_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT woocommerce_orders_pkey PRIMARY KEY (id, user_id),
  CONSTRAINT woocommerce_orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);